# Generated by Django 4.1.7 on 2024-01-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_num', models.IntegerField(null=True, unique=True, verbose_name='emp_num')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('account_id', models.CharField(max_length=10, unique=True, verbose_name='account_id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('affiliation', models.CharField(choices=[('HR', '総務人事部'), ('Sales', '営業部'), ('1st system', '第一システム部'), ('2nd system', '第二システム部'), ('3rd system', '第三システム部'), ('others', 'その他')], default='HR', max_length=10, verbose_name='affiliation')),
                ('retire_date', models.DateField(blank=True, null=True, verbose_name='retire_date')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuer')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
